#! /bin/bash

# copyright Andreas Schockenhoff 2001-2025, asc@ekf.de

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if ifclass DEBUG ; then
    # echo '  ' > $target/home/${username}/
    echo '. 100-make.eth1 && . 200-rc.local.fai && . 500-masq.me && . 600-get-config-space && sudo poweroff' > $target/home/${username}/do-all
    chmod a+x $target/home/${username}/do-all
    echo 'sudo chmod a+x /usr/local/sbin/rc.local && sudo /usr/local/sbin/rc.local' > $target/home/${username}/200-rc.local.fai
    chmod a+x $target/home/${username}/200-rc.local.fai

    echo 'echo "sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" >> $target/etc/rc.local' > $target/usr/local/sbin/make.nat
    echo 'echo "net.ipv4.ip_forward = 1"  >> /etc/sysctl.conf' >> $target/usr/local/sbin/make.nat
    chmod a+x $target/usr/local/sbin/make.nat 
    echo 'sudo make.nat' >> $target/home/${username}/500-masq.me 
    chmod a+x $target/home/${username}/500-masq.me

    # echo 'sudo reboot' > $target/home/${username}/150-reboot 
    echo 'sudo poweroff' > $target/home/${username}/990-poweroff
    chmod a+x $target/home/${username}/990-poweroff
    echo 'sudo reboot' > $target/home/${username}/reboot
    chmod a+x $target/home/${username}/reboot
    echo 'sudo poweroff' > $target/home/${username}/poweroff
    chmod a+x $target/home/${username}/poweroff

    echo 'sudo rm -rf /srv/fai/asc-fai-config ; cd /srv/fai && sudo git clone --branch server https://github.com/asc4asc/asc-fai-config.git' > $target/home/${username}/rm-git.clone.asc 
    echo 'systemctl restart isc-dhcp-server.service' > $target/home/${username}/systemctl_restart_isc-dhcp-server.service
    echo 'ansible-playbook -c=local --inventory=localhost, debian-lan-ansible/minimal.yml' > $target/home/${username}/ansible.demo 
    chmod a+x $target/home/${username}/ansible.demo
    echo 'git clone https://salsa.debian.org/andi/debian-lan-ansible' > $target/home/${username}/get.ansible
    chmod a+x $target/home/${username}/get.ansible
    echo 'git clone https://github.com/asc4asc/misc.git' > $target/home/${username}/get.misc4asc
    chmod a+x $target/home/${username}/get.misc4asc
    echo 'sudo dd if=/dev/zero of=/dev/sda count=1000 && sudo sync && sudo reboot' > $target/home/${username}/clean.sda
    chmod a+x $target/home/${username}/clean.sda
    $ROOTCMD chmod a+x /usr/local/sbin/make-auto-login-console
    $ROOTCMD make-auto-login-console -e ${username}
    echo ${username} "ALL=(ALL) NOPASSWD:ALL" >/tmp/tmp1
    cp /tmp/tmp1 ${target}/etc/sudoers.d/sudo4${username}  
    mkdir -p ${target}/home/${username}/.ssh
    # cat /home/id_rsa.pub >> $target/home/${username}/.ssh/authorized_keys # LATER!
fi
exit $error
