#! /bin/bash

# copyright Andreas Schockenhoff 2001-2025, asc@ekf.de

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if ifclass DEBUG ; then
    mkdir -p $target/home/${username}/faiserv
    # echo '  ' > $target/home/${username}/
    echo '. 100-make.eth && . 200-rc.local.fai && . 500-masq.me && . 600-get-config-space'> $target/home/${username}/faiserv/do-all
    chmod a+x $target/home/${username}/faiserv/do-all

    echo 'sudo chmod a+x /usr/local/sbin/rc.local && sudo /usr/local/sbin/rc.local' > $target/home/${username}/faiserv/200-rc.local.fai
    chmod a+x $target/home/${username}/faiserv/200-rc.local.fai

    echo 'echo "sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE" >> $target/etc/rc.local' > $target/usr/local/sbin/make.nat
    echo 'echo "net.ipv4.ip_forward = 1"  >> /etc/sysctl.conf' >> $target/usr/local/sbin/make.nat
    chmod a+x $target/usr/local/sbin/make.nat 
    echo 'sudo make.nat' >> $target/home/${username}/faiserv/500-masq.me 
    chmod a+x $target/home/${username}/faiserv/500-masq.me

    # echo 'sudo reboot' > $target/home/${username}/150-reboot 
    echo 'sudo poweroff' > $target/home/${username}/faiserv/990-poweroff
    chmod a+x $target/home/${username}/faiserv/990-poweroff
    echo 'sudo reboot' > $target/home/${username}/reboot
    chmod a+x $target/home/${username}/reboot
    echo 'sudo poweroff' > $target/home/${username}/poweroff
    chmod a+x $target/home/${username}/poweroff
    
    mkdir -p ${target}/home/${username}/.ssh
fi
exit $error
